# Generated by Django 6.0.2 on 2026-06-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ragistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField(max_length=15)),
                ('Institute_Name', models.CharField(max_length=15)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
