# Generated by Django 6.0.2 on 2026-06-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ragistration',
            name='Institute_Name',
        ),
        migrations.AddField(
            model_name='ragistration',
            name='institude',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ragistration',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
