# Generated by Django 6.0.2 on 2026-06-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0002_remove_ragistration_institute_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ragistration',
        ),
    ]
