# Generated by Django 6.0.2 on 2026-07-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkresult',
            name='path',
        ),
        migrations.RemoveField(
            model_name='networkresult',
            name='user',
        ),
        migrations.AddField(
            model_name='networkresult',
            name='result_json',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
