# Generated by Django 6.0.2 on 2026-07-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0006_remove_networkresult_result_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkresult',
            name='network_file',
        ),
        migrations.AddField(
            model_name='networkresult',
            name='name',
            field=models.CharField(default='latest', max_length=100),
        ),
        migrations.AddField(
            model_name='networkresult',
            name='network_path',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
