# Generated by Django 6.0.2 on 2026-08-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0007_remove_networkresult_network_file_networkresult_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageNetworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='latest', max_length=100)),
                ('network_path', models.CharField(max_length=500)),
                ('is_latest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
