# Generated by Django 6.0.2 on 2026-08-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0008_storagenetworkresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorageNetworkResult',
        ),
        migrations.AddField(
            model_name='networkresult',
            name='result_type',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkresult',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
